name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: west build -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }}
        env:
          ZMK_CONFIG: ${{ github.workspace }}
        strategy:
          matrix:
            include:
              - board: nice_nano_v2
                shield: IIGS
