name: Build ZMK Firmware (no-docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake ninja-build gperf ccache dfu-util \
            device-tree-compiler wget python3-pip python3-setuptools python3-wheel \
            xz-utils file make gcc g++ locales
          sudo locale-gen en_US.UTF-8

      - name: Install West + Zephyr Python deps
        run: |
          pip3 install --user west
          pip3 install --user -r https://raw.githubusercontent.com/zephyrproject-rtos/zephyr/main/scripts/requirements.txt
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Zephyr SDK
        run: |
          ZSDK_VER=0.16.8
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${ZSDK_VER}/zephyr-sdk-${ZSDK_VER}_linux-x86_64.tar.xz
          tar -xJf zephyr-sdk-${ZSDK_VER}_linux-x86_64.tar.xz
          mv zeph
