name: Build ZMK Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.3

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Initialize West (use this repo as ZMK_CONFIG)
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Build (nice_nano_v2 + IIGS shield)
        run: |
          west build -s zmk/app -d build/nice_nano_v2_IIGS -b nice_nano_v2 -- -DSHIELD=IIGS

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/nice_nano_v2_IIGS/zephyr/*.uf2
